version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: payflowdb
#    volumes:
#      - ./data:/var/lib/postgresql/data
#  app:
#    build:
#      context: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres
